/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import static Koneksi.DatabaseConnection.getConnection;
import Koneksi.koneksi;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author NANRC
 */
public class laporanBarang extends javax.swing.JPanel {

    /**
     * Creates new form dataBarang1
     */
    public laporanBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        laporanPemesananBarang = new Form.customButton();
        laporanDataBarang = new Form.customButton();
        laporanBarangMasuk = new Form.customButton();
        laporanBarangKeluar = new Form.customButton();

        setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 0));

        laporanPemesananBarang.setText("PEMESANAN SEMENTARA");
        laporanPemesananBarang.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        laporanPemesananBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanPemesananBarangActionPerformed(evt);
            }
        });
        jPanel2.add(laporanPemesananBarang);

        laporanDataBarang.setText("DATA BARANG");
        laporanDataBarang.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        laporanDataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanDataBarangActionPerformed(evt);
            }
        });
        jPanel2.add(laporanDataBarang);

        laporanBarangMasuk.setText("BARANG MASUK");
        laporanBarangMasuk.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        laporanBarangMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanBarangMasukActionPerformed(evt);
            }
        });
        jPanel2.add(laporanBarangMasuk);

        laporanBarangKeluar.setText("BARANG KELUAR");
        laporanBarangKeluar.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        laporanBarangKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                laporanBarangKeluarActionPerformed(evt);
            }
        });
        jPanel2.add(laporanBarangKeluar);

        add(jPanel2, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void laporanBarangMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanBarangMasukActionPerformed
       try {
        String reportPath = "src/report/laporanBarangMasuk.jasper";
        Connection conn = getConnection();
        
        HashMap<String, Object> parameters = new HashMap<>();
        JasperPrint print = JasperFillManager.fillReport(reportPath,parameters,conn);
        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Tidak dapat menampilkan report:" + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_laporanBarangMasukActionPerformed

    private void laporanDataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanDataBarangActionPerformed
        try {
        String reportPath = "src/report/dataBarang.jasper";
        Connection conn = getConnection();
        
        HashMap<String, Object> parameters = new HashMap<>();
        JasperPrint print = JasperFillManager.fillReport(reportPath,parameters,conn);
        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Tidak dapat menampilkan report:" + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_laporanDataBarangActionPerformed

    private void laporanPemesananBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanPemesananBarangActionPerformed
        try {
        String reportPath = "src/report/laporanPemesananSementara.jasper";
        Connection conn = getConnection();
        
        HashMap<String, Object> parameters = new HashMap<>();
        JasperPrint print = JasperFillManager.fillReport(reportPath,parameters,conn);
        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Tidak dapat menampilkan report:" + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_laporanPemesananBarangActionPerformed

    private void laporanBarangKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_laporanBarangKeluarActionPerformed
        try {
        String reportPath = "src/report/laporanBarangKeluar.jasper";
        Connection conn = getConnection();
        
        HashMap<String, Object> parameters = new HashMap<>();
        JasperPrint print = JasperFillManager.fillReport(reportPath,parameters,conn);
        JasperViewer viewer = new JasperViewer(print, false);
        viewer.setVisible(true);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Tidak dapat menampilkan report:" + e.getMessage(),"Error",JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_laporanBarangKeluarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private Form.customButton laporanBarangKeluar;
    private Form.customButton laporanBarangMasuk;
    private Form.customButton laporanDataBarang;
    private Form.customButton laporanPemesananBarang;
    // End of variables declaration//GEN-END:variables

}