/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Form;

import java.awt.Color;
import java.awt.List;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;


public class MenuUtama extends javax.swing.JFrame {
    private final User loggedInUser;
    

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama(User user) {
        this.loggedInUser = user;
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        execute();
        addMenu();
        Home();
        lblSelamatDatang.setText("Selamat Datang, " + user.getUsername());
    }

    MenuUtama() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pn_navbar = new javax.swing.JPanel();
        lblSelamatDatang = new javax.swing.JLabel();
        pn_sidebar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pn_menu = new javax.swing.JPanel();
        pn_content = new javax.swing.JPanel();
        pn_utama = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 153));

        pn_navbar.setBackground(new java.awt.Color(8, 44, 37));
        pn_navbar.setPreferredSize(new java.awt.Dimension(894, 70));

        lblSelamatDatang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSelamatDatang.setForeground(new java.awt.Color(255, 255, 255));
        lblSelamatDatang.setText("Selamat Datang");

        javax.swing.GroupLayout pn_navbarLayout = new javax.swing.GroupLayout(pn_navbar);
        pn_navbar.setLayout(pn_navbarLayout);
        pn_navbarLayout.setHorizontalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_navbarLayout.createSequentialGroup()
                .addContainerGap(692, Short.MAX_VALUE)
                .addComponent(lblSelamatDatang)
                .addGap(78, 78, 78))
        );
        pn_navbarLayout.setVerticalGroup(
            pn_navbarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_navbarLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(lblSelamatDatang)
                .addGap(24, 24, 24))
        );

        getContentPane().add(pn_navbar, java.awt.BorderLayout.PAGE_START);

        pn_sidebar.setBackground(new java.awt.Color(255, 255, 255));
        pn_sidebar.setPreferredSize(new java.awt.Dimension(250, 495));

        jScrollPane1.setBorder(null);

        pn_menu.setBackground(new java.awt.Color(255, 255, 255));
        pn_menu.setLayout(new javax.swing.BoxLayout(pn_menu, javax.swing.BoxLayout.Y_AXIS));
        jScrollPane1.setViewportView(pn_menu);

        javax.swing.GroupLayout pn_sidebarLayout = new javax.swing.GroupLayout(pn_sidebar);
        pn_sidebar.setLayout(pn_sidebarLayout);
        pn_sidebarLayout.setHorizontalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_sidebarLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                .addContainerGap())
        );
        pn_sidebarLayout.setVerticalGroup(
            pn_sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        getContentPane().add(pn_sidebar, java.awt.BorderLayout.LINE_START);

        pn_content.setBackground(new java.awt.Color(255, 255, 255));

        pn_utama.setBackground(new java.awt.Color(255, 255, 255));
        pn_utama.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout pn_contentLayout = new javax.swing.GroupLayout(pn_content);
        pn_content.setLayout(pn_contentLayout);
        pn_contentLayout.setHorizontalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, 644, Short.MAX_VALUE)
        );
        pn_contentLayout.setVerticalGroup(
            pn_contentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_utama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(pn_content, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(912, 587));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

    java.awt.EventQueue.invokeLater(() -> {
        // Buat user dummy untuk testing
        User dummyUser = new User(); // Pastikan kelas User ada
        new MenuUtama(dummyUser).setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSelamatDatang;
    private javax.swing.JPanel pn_content;
    private javax.swing.JPanel pn_menu;
    private javax.swing.JPanel pn_navbar;
    private javax.swing.JPanel pn_sidebar;
    private javax.swing.JPanel pn_utama;
    // End of variables declaration//GEN-END:variables

    private void execute() {
        ImageIcon iconHome = new ImageIcon(getClass().getResource("/gambar/Home Page.png"));
        ImageIcon iconMaster = new ImageIcon(getClass().getResource("/gambar/Master Data.png"));
        ImageIcon iconTransaksi = new ImageIcon(getClass().getResource("/gambar/Transaksi.png"));
        ImageIcon iconReport = new ImageIcon(getClass().getResource("/gambar/Report.png"));
        ImageIcon iconBarang = new ImageIcon(getClass().getResource("/gambar/Product.png"));
        ImageIcon iconDistributor = new ImageIcon(getClass().getResource("/gambar/Supplier.png"));
        ImageIcon iconUser = new ImageIcon(getClass().getResource("/gambar/User1.png"));
        ImageIcon iconPemesanan = new ImageIcon(getClass().getResource("/gambar/Pemesanan.png"));
        ImageIcon iconBarangMasuk = new ImageIcon(getClass().getResource("/gambar/Barang Masuk.png"));
        ImageIcon iconBarangKeluar = new ImageIcon(getClass().getResource("/gambar/Barang Keluar.png"));
        ImageIcon iconLogout = new ImageIcon(getClass().getResource("/gambar/Logout.png"));
        
        Menu_item menuHome = new Menu_item(iconHome, false, null, "Home", e -> {
        pn_utama.removeAll();
        pn_utama.add(new content_bg()); 
        pn_utama.repaint();
        pn_utama.revalidate();
        });
        
        Menu_item masterBarang1 = new Menu_item(null, true, iconBarang, "Data Barang", e -> {
        pn_utama.removeAll();
        pn_utama.add(new dataBarang());
        pn_utama.repaint();
        pn_utama.revalidate();
        });
        
        Menu_item masterBarang2 = new Menu_item(null, true, iconBarang, "Data Jenis Barang", e -> {
        pn_utama.removeAll();
        pn_utama.add(new dataJenisBarang());
        pn_utama.repaint();
        pn_utama.revalidate();
        });
        
        Menu_item masterBarang3 = new Menu_item(null, true, iconDistributor, "Data Distributor", e -> {
        pn_utama.removeAll();
        pn_utama.add(new dataDistributor());
        pn_utama.repaint();
        pn_utama.revalidate();
        });
        
        Menu_item masterBarang4 = new Menu_item(null, true, iconUser, "Data Pengguna", e -> {
        pn_utama.removeAll();
        pn_utama.add(new dataPengguna());
        pn_utama.repaint();
        pn_utama.revalidate();
        });

        
        Menu_item Transaksi1 = new Menu_item(null, true, iconPemesanan, "Pemesanan Sementara", e -> {
        pn_utama.removeAll();
        pn_utama.add(new pemesananBarang());
        pn_utama.repaint();
        pn_utama.revalidate();
        });
        
        Menu_item Transaksi2 = new Menu_item(null, true, iconBarangMasuk, "Barang Masuk", e -> {
        pn_utama.removeAll();
        pn_utama.add(new barangMasuk());
        pn_utama.repaint();
        pn_utama.revalidate();
        });
        
        Menu_item Transaksi3 = new Menu_item(null, true, iconBarangKeluar, "Barang Keluar", e -> {
        pn_utama.removeAll();
        pn_utama.add(new barangKeluar());
        pn_utama.repaint();
        pn_utama.revalidate();
        });
        
        Menu_item menuReport = new Menu_item(iconReport, false, null, "Laporan Barang", e -> {
        pn_utama.removeAll();
        pn_utama.add(new laporanBarang());
        pn_utama.repaint();
        pn_utama.revalidate();
        });
        
        Menu_item menuLogout = new Menu_item(iconLogout, false, null, "Logout", e -> {
        int confirm = JOptionPane.showConfirmDialog(
        null,
        "Yakin ingin logout?",
        "Konfirmasi Logout",
        JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
        // Tutup MenuUtama dan buka LoginForm
        JFrame topFrame = (JFrame) SwingUtilities.getWindowAncestor(pn_utama);
        topFrame.dispose(); // Tutup MenuUtama

        new Form_login().setVisible(true); // Tampilkan form login
        }
        });

        
        Menu_item menuMaster = new Menu_item(iconMaster, false, null, "Master Data", null, masterBarang1, masterBarang2, masterBarang3, masterBarang4);
        Menu_item menuTransaksi = new Menu_item(iconTransaksi, false, null, "Transaksi", null, Transaksi1, Transaksi2, Transaksi3);    
        addMenu(menuHome,menuMaster,menuTransaksi,menuReport,menuLogout);
        
        
    }

    private void addMenu(Menu_item... menu) {
        for (int i = 0; i < menu.length; i++) {
            pn_menu.add(menu[i]);
            ArrayList<Menu_item> subMenu = menu[i].getSubMenu();
            for (Menu_item m : subMenu) {
                addMenu(m);
            }
        }
        pn_menu.revalidate();
    }

    private void Home() {
    pn_utama.removeAll();
    pn_utama.add(new content_bg()); // ganti dengan nama panel home kamu
    pn_utama.repaint();
    pn_utama.revalidate();
}
}
